---

dircolors_dest_file: /etc/DIR_COLORS
dircolors_become: yes

homebrew_caskroom_dir: '/usr/local/Caskroom'

homebrew_taps:
  - homebrew/dupes
  - homebrew/science

homebrew_casks:
  - atom
  - dash
  - docker-beta
  - google-chrome
  - iterm2
  - slack

packages:
  - ansible
  - awscli
  - fish
  - fzf
  - git-extras
  - git-lfs
  - hub
  - neovim
  - node
  - numpy
  - python
  - python3
  - ripgrep
  - rsync

dns_restart_commands:
  - "dscacheutil -flushcache"
  - "killall -HUP mDNSResponder"
