---

- name: colors
  hosts: all
  gather_facts: yes

  tasks:
    - block:
        - name: download | color scheme(s)
          get_url:
            url: "{{ item }}"
            dest: "{{ ansible_user_dir }}/Downloads"
          with_items:
            - https://raw.githubusercontent.com/chriskempson/base16-iterm2/master/base16-tomorrow.dark.256.itermcolors
            - https://cdn.rawgit.com/stoeffel/material-iterm/1.0.2/material-dark.itermcolors
            - https://raw.githubusercontent.com/chriskempson/base16-iterm2/master/base16-google.dark.256.itermcolors

        - name: INSTALL INSTRUCTIONS
          debug:
            msg: '1. In iTerm2, go to Preferences > Profiles > Colors   2. Click on Load Presets > Import & import the theme from ~/Downloads/<theme>'
      when: ansible_distribution == 'MacOSX'
