---

- name: github
  hosts: all

  vars:
    state: present

  roles:
    - role: mkwmms.github
      username: mkwmms
      email: mkwmms@users.noreply.github.com
      install_state: "{{ state }}"
      # configuration_state: "{{ state }}"
