---

- name: github
  hosts: all
  gather_facts: yes

  vars_files:
    - secrets.yml

  vars:
    state: present
    repos:
      - "{{ github_username }}/BYU"
      - "{{ github_username }}/ansible-coreutils"
      - "{{ github_username }}/ansible-dircolors"
      - "{{ github_username }}/ansible-fish"
      - "{{ github_username }}/ansible-github"
      - "{{ github_username }}/ansible-gnu-tools"
      - "{{ github_username }}/ansible-neovim"
      - "{{ github_username }}/ansible-node"
      - "{{ github_username }}/ansible-osx"
      - "{{ github_username }}/ansible-pure"
      - "{{ github_username }}/ansible-ruby"
      - "{{ github_username }}/ansible-xcode"
      - "{{ github_username }}/ansible-xdg"
      - "{{ github_username }}/ansible-z"
      - "{{ github_username }}/dotstrap"

  roles:
    - role: dotstrap.github
      username: "{{ github_username }}"
      email: "{{ github_email }}"
      install_state: "{{ state }}"
      configuration_state: "{{ state }}"

  tasks:
    - name: git | clone repos
      git:
        repo: git@github.com:{{ item }}.git
        dest: "{{ ansible_user_dir }}/Documents/Developer/{{ item | basename }}"
        accept_hostkey: yes
      with_items: "{{ repos }}"
