- hosts: all

  vars_files:
    - secrets.yml

  pre_tasks:
    - name: setup | fish homebrew env
      command: >
        fish -c "set -Ux HOMEBREW_EDITOR nvim;
                 set -Ux HOMEBREW_GITHUB_API_TOKEN {{ homebrew_github_api_token }}
                 set -Ux HOMEBREW_CASK_OPTS --appdir=/Applications --caskroom=/usr/local/Caskroom"
      when: (ansible_distribution == 'MacOSX') and (ansible_user_shell | basename == 'fish')
      tags:
        - bootstrap
        - configure

  roles:
    - role: geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'
      tags:
        - bootstrap
        - install
        - update
