---

- src: dotstrap.dircolors
- src: dotstrap.fish
- src: dotstrap.github
- src: dotstrap.gnu-tools
- src: dotstrap.neovim
- src: dotstrap.node
- src: dotstrap.osx
- src: dotstrap.pure
- src: dotstrap.ruby
- src: dotstrap.sensible
- src: dotstrap.ssh
- src: dotstrap.xcode
- src: dotstrap.xdg
- src: dotstrap.z
