---
- name: shell
  gather_facts: yes
  hosts: all

  roles:
    - role: dotstrap.sensible
      tags: sensible
    - role: dotstrap.dircolors
      tags: dircolors
    - role: dotstrap.pure
      tags: pure
    - role: dotstrap.fzf
      tags: fzf
    - role: dotstrap.enhancd
      tags: enhancd
