---
- hosts: all
  tasks:
     - group_by: key="{{ ansible_distribution }}"

- name: shell
  hosts: all

  roles:
    - role: dotstrap.fish
      tags: fish 
    - role: dotstrap.sensible
      tags: sensible
    - role: dotstrap.dircolors
      tags: dircolors
    - role: dotstrap.pure
      tags: pure
    - role: dotstrap.fzf
      tags: fzf
    - role: dotstrap.enhancd
      tags: enhancd
