---
galaxy_info:
  author: mkwmms
  description: "Configure ssh."
  license: GPLv3
  # min_ssh_version: 2.0
  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any
    - name: GenericBSD
      versions:
        - all
        - any
    - name: GenericLinux
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - ssh

dependencies: []
