---
# tasks file for ansible

# - name: setup | install
  # include: install.yml
  # when: ansible_install_state == 'present'

- name: setup | configure
  include: configure.yml
  when: ansible_configure_state == 'present'
  tags:
    - bootstrap
    - bootstrap_ansible
    - configure
    - configure_ansible
